app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())

    pitches = db.relationship('Pitch',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)
    
    def __repr__(self):         #check if positioning is correct
        return f'User {self.username}'

class Pitch(db.Model):

    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    mycategory = db.Column(db.String)
    mypitch = db.Column(db.String)

    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,id):
        pitches = Pitch.query.filter_by(pitch_id=id).all()
        return pitches

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, StringField
from flask_wtf.file import FileField, FileAllowed
# import the Required class validator that will prevent the user from submitting the form without Inputting a value
from wtforms.validators import InputRequired,Length
# from flask_login import current_user 

class UpdateProfile(FlaskForm):
    bio = TextAreaField('How are you feeling today?',validators = [InputRequired(), Length(min=5, max=20)])
    # picture= FileField('Update Profile Picture', validators= [FileAllowed(['jpg','png'])])
    submit = SubmitField('Update')

class PitchForm(FlaskForm):
    category= StringField('Category title',validators=[InputRequired()], render_kw={"placeholder": "Enter industry related fields e.g technology, agriculture, entertainment, etc"})
    pitch= TextAreaField('Input your pitch', validators=[InputRequired(), Length(min=10, max=100)], render_kw={"placeholder": "Your pitch should not exceed 100 characters"})
    submit = SubmitField('Post')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

mail = Mail()

photos = UploadSet('photos',IMAGES)
bootstrap = Bootstrap()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):

    app = Flask(__name__)

    mail.init_app(app)
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #Creating the app configurations
    app.config.from_object(config_options[config_name])

    #Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    #configure UploadSet
    configure_uploads(app,photos)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required
from ..models import  User,Pitch
from .forms import UpdateProfile, PitchForm
from ..import db,photos

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    return render_template('index.html')

# Input! the flask_login decorator '@login_required' that will intercept a request and check if 
# the user is authenticated and if not the user will be redirected to the login page.

@main.route('/user/<uname>',methods = ['GET','POST'])
@login_required
def profile(uname):
    form = UpdateProfile()
    user = User.query.filter_by(username = uname).first()
    
    pitches = Pitch.query.filter_by(user_id = user.id).all()

    if user is None:
        abort(404)

    if form.validate_on_submit():
            user.bio = form.bio.data

            db.session.add(user)
            db.session.commit()

            return redirect(url_for('.profile',uname=user.username))

    return render_template("profile/profile.html", user = user, form = form, pitches = pitches)

@main.route('/user/pitch/<uname>',methods = ['GET','POST'])
@login_required
def new_pitch(uname):

    pform = PitchForm()
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    if pform.validate_on_submit():
        category = pform.category.data
        pitch = pform.pitch.data

        new_pitch = Pitch(mycategory=category, mypitch= pitch, user_id = user.id)

         # Updated pitch instance
        new_pitch.save_pitch()

        return redirect(url_for('main.profile', uname = uname))

    return render_template('new_pitch.html', pitch_form = pform)

@main.route('/pitches', methods = ['GET','POST'])
def pitches():
    pitches = Pitch.query.all()

    return render_template('pitches.html', pitches = pitches)

app/templates/base.html
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">

<!-- Flask-Bootstrap contains its own base.html which has defined blocks that we can refer to and add our own data. -->
{% extends 'bootstrap/base.html'%}

<!-- Navblock -->
{% block navbar %}     
    {% include 'navbar.html' %}      <!--includes control block to include our _navbar.html_ file to that section of the base.html template.-->
{% endblock %}      <!--when you start a block you should end it-->


<!-- Styles block -->
{% block styles %}

{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/base.css')}}">

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

<!-- Styles block -->
{% block styles %}

    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">

{% endblock %}

<!-- Content block -->
{% block content %}

<div class="container space">
    <div class="row">
        <div class="col-md-12">
            <h1 class="title"> Pitch & Win </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <p class="text"> Pitch your idea and stand a chance to win! </p>

            {% if current_user.is_authenticated %}
            <a href="{{url_for('main.pitches')}}"> <button class="button buttonx ">View Pitches</button>
            {% else %}
            <a href="{{url_for('auth.register')}}"> <button class="button button1 ">Create an account</button>
            <a href="{{url_for('main.pitches')}}"> <button class="button button2 ">View Pitches</button>
            {%endif%}
        </div>
    </div>
</div>

{% endblock%}

app/templates/navbar.html
<style>

.nav>li>a:focus, .nav>li>a:hover {
    background-color: rgb(139, 139, 214);
}

</style>

<div class="navbar navbar-light" style="background-color: rgb(153, 153, 228)" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> <b>Perfect Pitch</b></a>
        </div>
        <div class="navbar-collapse collapse">

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <!-- <li style="color:rgb(255, 255, 255);padding:15px;">{{current_user.username}}</li> -->
                <!--create a link on our navbar to direct us to the profile page. Link is only visible if user is authenticated-->
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Log in</a></li>
                {%endif%}
            </ul>

        </div>

    </div>
</div>

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

<!-- Styles block -->
{% block styles %}

{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/pitch.css')}}">

{% endblock %}

{% block content %}
    <div class="container">


        <div class="col-md-6">
            <h1> Enter your Pitch</h1>
            {{ wtf.quick_form(pitch_form) }}
        </div>

    </div>

{% endblock %}

app/templates/pitches.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="row">

            {% for pitch in pitches %}
  
            <h2> Category: {{pitch.mycategory}} </h2>
            <p> 1 minute pitch: {{pitch.mypitch}} </p>
            <hr>
  
            {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

<!-- Styles block -->
{% block styles %}

{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/profile.css')}}">

{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <!-- displaying  Username-->
    <div class="col-md-6 myprofile">

      <h1>My Profile</h1>

<!-- Displaying profile pic -->      
     
        <img src="{{url_for('static',filename='default.png')}}" alt="" class="img-thumbnail imgsize">
      
<!-- Display user name and bio -->
        <div class="userdetails">
          <h3 class="p_space"> {{user.username| capitalize}} </h3>

          {% if user.bio %}
          <p class="mybio"> {{user.bio}}</p>
          {%else%}
          <p> {{user.username| capitalize}} has no bio </p>
          {% endif %}
       </div>

<!-- Display form -->
          <div class="updateform">
            {{wtf.quick_form(form)}}
          </div>
           
        
          </ul>

      </div>


    <!-- Display pitch section -->
    <div class="col-md-6">
      <h1 class="title">My Pitches</h1>
  
         <a href="{{url_for('main.new_pitch',uname=user.username)}}"> <button class="button buttonpost ">Post a pitch</button></a>
          {% for pitch in pitches %}
  
          <h2> {{pitch.mycategory}} </h2>
          <p> {{pitch.mypitch}} </p>
          <hr>

          {% endfor %}
      </div>
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
<!-- {% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %} -->